### ISSUE TITLE
Uploading NFTS to mainnet-beta arvweave not enough funds problem

### ISSUE THREAD

**Issue by avanti36** [solana-labs/wallet-adapter#272]
Hello! I am trying to upload 3 NFTs to mainnet on     "storage": "arweave-sol",
 (balance on wallet is 0.6 Sol, seems to be enough for my test). Each time I get this error about funds. Could you please, help how to deal with this? 

Uploading Size 3 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 3 file pair(s) totaling 0.065MB.
Uploading bundle via bundlr... in multiple transactions
0.000009587 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data
    at Uploader.<anonymous> (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 2) Error: Not enough funds to send data
    at Uploader.<anonymous> (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Not enough funds to send data
    at Uploader.<anonymous> (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jordansexton** [comment]
This isn't the right place for issues with Arweave.
