### ISSUE TITLE
No wallet options when selecting wallet

### ISSUE THREAD

**Issue by DitJee** [solana-labs/wallet-adapter#412]
**Describe the bug**
The wallet options are nowhere to be found where pressing `select wallet` button. Moreover, if we pressed `Get Started` the error which will be posted below will occur.

**To Reproduce**
1. Go to 'http://localhost:4000/#/home'
![image](https://user-images.githubusercontent.com/56587469/167402397-0eb0b744-4f5a-44d0-9641-67edc2324f38.png)

2. Click on 'Select Wallet'
![image](https://user-images.githubusercontent.com/56587469/167402443-65e5ed66-74a8-4248-a620-4fbef6dba264.png)

3. See error
![image](https://user-images.githubusercontent.com/56587469/167402476-250c5a7c-2103-4ecd-9895-b6410ddd2066.png)

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'adapter')
    at onClick (WalletModal.mjs?8e84:122:61)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?ac89:4070:1)
    at executeDispatch (react-dom.development.js?ac89:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js?ac89:8275:1)
    at processDispatchQueue (react-dom.development.js?ac89:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js?ac89:8299:1)
    at eval (react-dom.development.js?ac89:8508:1)
    at batchedEventUpdates$1 (react-dom.development.js?ac89:22396:1)
    at batchedEventUpdates (react-dom.development.js?ac89:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?ac89:8507:1)
    at attemptToDispatchEvent (react-dom.development.js?ac89:6005:1)
    at dispatchEvent (react-dom.development.js?ac89:5924:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at discreteUpdates$1 (react-dom.development.js?ac89:22413:1)
    at discreteUpdates (react-dom.development.js?ac89:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js?ac89:5889:1)
next-dev.js?3515:25 You have tried to  read "wallets" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
    at WalletModal (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModal.mjs:21:24)
    at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
    at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
    at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
    at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
    at div
    at header
    at div
    at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
    at div
    at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
    at div
    at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
    at div
    at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
    at StartingPage
    at div
    at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
window.console.error @ next-dev.js?3515:25
next-dev.js?3515:25 You have tried to  read "publicKey" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
    at WalletMultiButton (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletMultiButton.mjs:19:30)
    at div
    at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
    at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
    at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
    at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
    at div
    at header
    at div
    at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
    at div
    at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
    at div
    at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
    at div
    at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
    at StartingPage
    at div
    at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
window.console.error @ next-dev.js?3515:25
next-dev.js?3515:25 You have tried to  read "wallet" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
    at WalletMultiButton (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletMultiButton.mjs:19:30)
    at div
    at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
    at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
    at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
    at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
    at div
    at header
    at div
    at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
    at div
    at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
    at div
    at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
    at div
    at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
    at StartingPage
    at div
    at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome
 - Version:100.0.4896.127 (Official Build) (64-bit)

**Additional context**
The code to the repo is as followed => https://github.com/DitJee/Roblox-Marketplace-Clone/blob/main/Frontend/frontend-react-app/components/Wallet.tsx

**Comment by jkchuynh829** [comment]
> **Describe the bug** The wallet options are nowhere to be found where pressing `select wallet` button. Moreover, if we pressed `Get Started` the error which will be posted below will occur.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'http://localhost:4000/#/home'
>    ![image](https://user-images.githubusercontent.com/56587469/167402397-0eb0b744-4f5a-44d0-9641-67edc2324f38.png)
> 2. Click on 'Select Wallet'
>    ![image](https://user-images.githubusercontent.com/56587469/167402443-65e5ed66-74a8-4248-a620-4fbef6dba264.png)
> 3. See error
>    ![image](https://user-images.githubusercontent.com/56587469/167402476-250c5a7c-2103-4ecd-9895-b6410ddd2066.png)
> 
> ```js
> Uncaught TypeError: Cannot read properties of undefined (reading 'adapter')
>     at onClick (WalletModal.mjs?8e84:122:61)
>     at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
>     at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
>     at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?ac89:4070:1)
>     at executeDispatch (react-dom.development.js?ac89:8243:1)
>     at processDispatchQueueItemsInOrder (react-dom.development.js?ac89:8275:1)
>     at processDispatchQueue (react-dom.development.js?ac89:8288:1)
>     at dispatchEventsForPlugins (react-dom.development.js?ac89:8299:1)
>     at eval (react-dom.development.js?ac89:8508:1)
>     at batchedEventUpdates$1 (react-dom.development.js?ac89:22396:1)
>     at batchedEventUpdates (react-dom.development.js?ac89:3745:1)
>     at dispatchEventForPluginEventSystem (react-dom.development.js?ac89:8507:1)
>     at attemptToDispatchEvent (react-dom.development.js?ac89:6005:1)
>     at dispatchEvent (react-dom.development.js?ac89:5924:1)
>     at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
>     at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
>     at discreteUpdates$1 (react-dom.development.js?ac89:22413:1)
>     at discreteUpdates (react-dom.development.js?ac89:3756:1)
>     at dispatchDiscreteEvent (react-dom.development.js?ac89:5889:1)
> next-dev.js?3515:25 You have tried to  read "wallets" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
>     at WalletModal (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModal.mjs:21:24)
>     at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
>     at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
>     at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
>     at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
>     at div
>     at header
>     at div
>     at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
>     at div
>     at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
>     at div
>     at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
>     at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
>     at div
>     at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
>     at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
>     at StartingPage
>     at div
>     at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
>     at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
>     at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
>     at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
>     at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
>     at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
> window.console.error @ next-dev.js?3515:25
> next-dev.js?3515:25 You have tried to  read "publicKey" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
>     at WalletMultiButton (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletMultiButton.mjs:19:30)
>     at div
>     at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
>     at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
>     at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
>     at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
>     at div
>     at header
>     at div
>     at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
>     at div
>     at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
>     at div
>     at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
>     at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
>     at div
>     at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
>     at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
>     at StartingPage
>     at div
>     at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
>     at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
>     at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
>     at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
>     at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
>     at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
> window.console.error @ next-dev.js?3515:25
> next-dev.js?3515:25 You have tried to  read "wallet" on a WalletContext without providing one. Make sure to render a WalletProvider as an ancestor of the component that uses WalletContext 
>     at WalletMultiButton (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletMultiButton.mjs:19:30)
>     at div
>     at WalletModalProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react-ui/lib/esm/WalletModalProvider.mjs:11:32)
>     at WalletProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/WalletProvider.mjs:21:27)
>     at ConnectionProvider (webpack-internal:///./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.mjs:11:31)
>     at Wallet (webpack-internal:///./components/Wallet.tsx:28:66)
>     at div
>     at header
>     at div
>     at PostLoginHeader (webpack-internal:///./components/PostLogin/PostLoginHeader.tsx:18:27)
>     at div
>     at TrackVisibility (webpack-internal:///./node_modules/react-on-screen/lib/TrackVisibility.js:30:28)
>     at div
>     at Home (webpack-internal:///./components/PostLogin/Home.tsx:24:62)
>     at Routes (webpack-internal:///./node_modules/react-router/index.js:920:5)
>     at div
>     at Router (webpack-internal:///./node_modules/react-router/index.js:854:15)
>     at HashRouter (webpack-internal:///./node_modules/react-router-dom/index.js:152:5)
>     at StartingPage
>     at div
>     at MyApp (webpack-internal:///./pages/_app.tsx:42:27)
>     at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
>     at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
>     at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
>     at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
>     at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)
> ```
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser  chrome
> * Version:100.0.4896.127 (Official Build) (64-bit)
> 
> **Additional context** The code to the repo is as followed => https://github.com/DitJee/Roblox-Marketplace-Clone/blob/main/Frontend/frontend-react-app/components/Wallet.tsx

Ran into this same problem. Curious if @DitJee found a solution?

**Comment by ElasticBottle** [comment]
@DitJee  did you ever figure out the solution to this problem?

**Comment by DitJee** [comment]
@ElasticBottle Hi there! 
I did find the solution which is to `update the react project to the latest version`. 
Hope this will work for you too!

**Comment by ElasticBottle** [comment]
Sweet, will try that thanks! I'm assuming you're on react ^18?

**Comment by DitJee** [comment]
> Sweet, will try that thanks! I'm assuming you're on react ^18?

Yes, I'm on `react: 18.1.0`

**Comment by kevinz420** [comment]
i tried updating to latest react and still no luck. did you do anything else after updating?

**Comment by DitJee** [comment]
@kevinz420 try starting from an empty project and see if it work or not. Cus in my case, updating the react version alone did not work. I had to start a new project and move all files from the old to the new one.

**Comment by moraispgsi** [comment]
I know this is already closed, however I want to contribute to this as I found a similar problem and managed to solve it. I noticed that in my setup I was getting the error: "You have tried to ## on a WalletContext without providing one...", turns out it was because the useWallet context was duplicated, libraries have two separate build folders, 'esm' and 'cjs', the library was importing from cjs while my app was importing from esm, creating two instances. 

To fix it I had to import the library with the suffix /lib/cjs.

Hope this helps some people out.

**Comment by jordansexton** [comment]
All packages have been updated: https://twitter.com/jordaaash/status/1541927694786600961

The library now supports React 17 and 18, and there's a Create React App 5 starter project. Please try again!

**Comment by sunlee-newyork** [comment]
> I know this is already closed, however I want to contribute to this as I found a similar problem and managed to solve it. I noticed that in my setup I was getting the error: "You have tried to ## on a WalletContext without providing one...", turns out it was because the useWallet context was duplicated, libraries have two separate build folders, 'esm' and 'cjs', the library was importing from cjs while my app was importing from esm, creating two instances.
> 
> To fix it I had to import the library with the suffix /lib/cjs.
> 
> Hope this helps some people out.

thanks for sharing! i'm getting the same issue too. could you explain how you debugged the duplicate context?

**Comment by jordansexton** [comment]
@sunlee-newyork what versions of the packages are you running?

**Comment by sunlee-newyork** [comment]
> @sunlee-newyork what versions of the packages are you running?

"@solana/wallet-adapter-base": "^0.9.18",
"@solana/wallet-adapter-material-ui": "^0.16.16",
"@solana/wallet-adapter-react": "^0.15.21-rc.0",
"@solana/wallet-adapter-react-ui": "^0.9.18",
"@solana/wallet-adapter-wallets": "^0.19.2",
"@solana/web3.js": "^1.31.0",

**Comment by jordansexton** [comment]
Ah, do this: https://twitter.com/jordaaash/status/1581804816979808258

The RC of the `wallet-adapter-react` package is conflicting with the version of the same package that `wallet-adapter-material-ui` and `wallet-adapter-react-ui` are using. Overriding it will fix them.

Also, you _probably_ don't want both the React UI and Material UI packages?

**Comment by sunlee-newyork** [comment]
> Ah, do this: https://twitter.com/jordaaash/status/1581804816979808258
> 
> The RC of the `wallet-adapter-react` package is conflicting with the version of the same package that `wallet-adapter-material-ui` and `wallet-adapter-react-ui` are using. Overriding it will fix them.
> 
> Also, you _probably_ don't want both the React UI and Material UI packages?

ah that was it, thanks. and yes i was migrating from `wallet-adapter-react-ui` to `wallet-adapter-material-ui` thanks for the reminder

**Comment by muckee** [comment]
I ran into the same issue just copy & pasting the example code into a fresh `create-react-app` skeleton with `react-app-rewired` installed for the polyfills, then attempting to import `useWallet` into a child element of the provider.

For me, the issue was resolved by replacing the line `const { useWallet } = require("@solana/wallet-adapter-react");` with `import { useWallet } from '@solana/wallet-adapter-react';`.

I'd already replaced the `require` statements with `import` statements elsewhere in my app. Will only work if you're using ES6+.

**Comment by misterjame** [comment]
I had the same problem. Adding the following line to my VITE configuration fixed it. I followed the official integration guide, only difference is I'm using yarn.

```js
  {resolve: {
    alias: {
      '@solana/wallet-adapter-react': path.resolve('./node_modules/@solana/wallet-adapter-react/lib/esm')
    }
  }}
