### ISSUE TITLE
Integration with next-i18next library

### ISSUE THREAD

**Issue by MotionForward** [solana-labs/wallet-adapter#429]
The user logs out from wallet when switching between locale pages in next js apps.
Is there a way to keep user logged in while switching between different languages?

WalletDisconnectedError
    at n.PhantomWalletAdapter._disconnected (adapter.mjs?441e:19:1)
    at n.o.register.u.emit (inpage.js:2:109362)
    at inpage.js:33:128280
    at c (inpage.js:2:47880)
    at Generator._invoke (inpage.js:2:47668)
    at Generator.next (inpage.js:2:48309)
    at inpage.js:33:124555
    at new Promise (<anonymous>)
    at Da (inpage.js:33:124300)
    at n.i._handleDisconnect (inpage.js:33:128124)
    at inpage.js:33:130219
    at c (inpage.js:2:47880)
    at Generator._invoke (inpage.js:2:47668)
    at Generator.next (inpage.js:2:48309)
    at inpage.js:33:124555
    at new Promise (<anonymous>)
    at Da (inpage.js:33:124300)
    at i._handleMessage (inpage.js:33:129006)
window.console.error @ next-dev.js?3515:32

WalletConnectionError: User rejected the request.
    at PhantomWalletAdapter.connect (adapter.mjs?441e:84:1)
    at async eval (WalletProvider.mjs?0273:77:1)

**Comment by Veterangrail** [comment]
> The user logs out from wallet when switching between locale pages in next js apps. Is there a way to keep user logged in while switching between different languages?
> 
> WalletDisconnectedError at n.PhantomWalletAdapter._disconnected (adapter.mjs?441e:19:1) at n.o.register.u.emit (inpage.js:2:109362) at inpage.js:33:128280 at c (inpage.js:2:47880) at Generator._invoke (inpage.js:2:47668) at Generator.next (inpage.js:2:48309) at inpage.js:33:124555 at new Promise () at Da (inpage.js:33:124300) at n.i._handleDisconnect (inpage.js:33:128124) at inpage.js:33:130219 at c (inpage.js:2:47880) at Generator._invoke (inpage.js:2:47668) at Generator.next (inpage.js:2:48309) at inpage.js:33:124555 at new Promise () at Da (inpage.js:33:124300) at i._handleMessage (inpage.js:33:129006) window.console.error @ next-dev.js?3515:32
> 
> WalletConnectionError: User rejected the request. at PhantomWalletAdapter.connect (adapter.mjs?441e:84:1) at async eval (WalletProvider.mjs?0273:77:1)

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by bijaypoudel1** [comment]
I am also facing same issue , wallet get auto disconnected while switching to another page.
It shows the console error

next-dev.js?3515:20 WalletDisconnectedError
    at PhantomWalletAdapter._disconnected (adapter.js?c296:21:1)
    at a.register.u.emit (inpage.js:3:375177)
    at inpage.js:48:246728
    at f (inpage.js:3:47880)
    at Generator._invoke (inpage.js:3:47668)
    at Generator.next (inpage.js:3:48309)
    at inpage.js:48:242985
    at new Promise (<anonymous>)
    at Di (inpage.js:48:242730)
    at i._handleDisconnect (inpage.js:48:246572)
    at inpage.js:48:248682
    at f (inpage.js:3:47880)
    at Generator._invoke (inpage.js:3:47668)
    at Generator.next (inpage.js:3:48309)
    at inpage.js:48:242985
    at new Promise (<anonymous>)
    at Di (inpage.js:48:242730)

**Comment by bijaypoudel1** [comment]
You can use useMemo hook for wallets connection and this will solve the WalletDisconnectedError while routing in next js.
  
```
const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new SlopeWalletAdapter(),
      new SolflareWalletAdapter({ network }),
    ],
    [network]
  );
```

**Comment by jordansexton** [comment]
Closing since I don't think this is a bug in Wallet Adapter specifically. You'll need to make sure the context and state doesn't get blown away by Next.
