### ISSUE TITLE
SendOneLamportToRandomAddress working, but not sending lamports

### ISSUE THREAD

**Issue by W3TFT** [solana-labs/wallet-adapter#553]
App.tsx
```tsx
import { WalletAdapterNetwork, WalletNotConnectedError } from '@solana/wallet-adapter-base';
import { ConnectionProvider, WalletProvider, useConnection, useWallet } from '@solana/wallet-adapter-react';
import { WalletConnectButton, WalletDisconnectButton, WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import { PhantomWalletAdapter, SlopeWalletAdapter, SolflareWalletAdapter } from '@solana/wallet-adapter-wallets';
import { clusterApiUrl, Keypair, SystemProgram, Transaction } from '@solana/web3.js';
import React, { FC, ReactNode, useMemo, useCallback, useState } from 'react';


require('./App.css');
require('@solana/wallet-adapter-react-ui/styles.css');

const App: FC = () => {
    return (
        <Context>
            <Content />
        </Context>
    );
};
export default App;


const Context: FC<{ children: ReactNode }> = ({ children }) => {
    // The network can be set to 'devnet', 'testnet', or 'mainnet-beta'.
    const network = WalletAdapterNetwork.Devnet;

    // You can also provide a custom RPC endpoint.
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    const wallets = useMemo(
        () => [
            /**
             * Select the wallets you wish to support, by instantiating wallet adapters here.
             *
             * Common adapters can be found in the npm package `@solana/wallet-adapter-wallets`.
             * That package supports tree shaking and lazy loading -- only the wallets you import
             * will be compiled into your application, and only the dependencies of wallets that
             * your users connect to will be loaded.
             */
            new PhantomWalletAdapter(),
            new SlopeWalletAdapter(),
            new SolflareWalletAdapter(),
        ],
        []
    );

    return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletModalProvider>{children}</WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
};

export const SendOneLamportToRandomAddress: FC = () => {
    const { connection } = useConnection();
    const { publicKey, sendTransaction } = useWallet();

    const onClick = useCallback(async () => {
        if (!publicKey) throw new WalletNotConnectedError();

        const transaction = new Transaction().add(
            SystemProgram.transfer({
                fromPubkey: publicKey,
                toPubkey: Keypair.generate().publicKey,
                lamports: 1,
            })
        );

        const {
            context: { slot: minContextSlot },
            value: { blockhash, lastValidBlockHeight }
        } = await connection.getLatestBlockhashAndContext();

        const signature = await sendTransaction(transaction, connection, { minContextSlot });

        await connection.confirmTransaction({ blockhash, lastValidBlockHeight, signature });
    }, [publicKey, sendTransaction, connection]);

    return (
        <button onClick={onClick} disabled={!publicKey}>
            Send 1 lamport to a random address!
        </button>
    );
};

const Content: FC = () => {
    return (
        <div className="App">
            <WalletMultiButton />
            <WalletDisconnectButton />
            <SendOneLamportToRandomAddress />
        </div>
    );
};
```

index.tsx
```tsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';
import reportWebVitals from './reportWebVitals';
import { createRoot } from 'react-dom/client';
import { Buffer } from 'buffer';

// @ts-ignore
window.Buffer = window.Buffer || require('buffer').Buffer;

const container = document.getElementById('root')!;
const root = createRoot(container);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

i have this errors in browser console:
```

Phantom - RPC Error: failed to send transaction: Transaction simulation failed: Transaction results in an account (1) without insufficient funds for rent

WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Transaction results in an account (1) without insufficient funds for rent
    at PhantomWalletAdapter.sendTransaction (adapter.ts:189:1)
    at async WalletProvider.tsx:238:1
    at async App.tsx:80:1
    
Uncaught (in promise) WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Transaction results in an account (1) without insufficient funds for rent
    at PhantomWalletAdapter.sendTransaction (adapter.ts:189:1)
    at async WalletProvider.tsx:238:1
    at async App.tsx:80:1
    
WalletProvider.tsx:129 WalletDisconnectedError
    at PhantomWalletAdapter._disconnected (adapter.ts:255:1)
    at o.register.u.emit (inpage.js:3:109362)
    at inpage.js:34:135176
    at c (inpage.js:3:47880)
    at Generator._invoke (inpage.js:3:47668)
    at Generator.next (inpage.js:3:48309)
    at inpage.js:34:131451
    at new Promise (<anonymous>)
    at ds (inpage.js:34:131196)
    at i._handleDisconnect (inpage.js:34:135020)
```

p.s. im using this starter: https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/

**Comment by W3TFT** [comment]
> Ah, this is an issue with the example code then. The problem here is that accounts must be rent exempt, and 1 Lamport is not enough. The minimum Lamport balance of a system account is 890880.

So one thing i need to do is just change 1 to 890880+ lamports?

**Comment by W3TFT** [comment]
> I believe so, but try it out and let me know!

working, thank you a lot, big boss
