### ISSUE TITLE
WalletSendTransactionError: Blob.encode[recentBlockhash] requires (length 32) Uint8Array as src

### ISSUE THREAD

**Issue by reasje** [solana-labs/wallet-adapter#769]
**Describe the bug**
I have a code which is on NextsJs React code and runs when I run it with `npm run dev`, But when I build it with `npm run build` followed by `pm2 restart rps` I get this error:

```
WalletSendTransactionError: Blob.encode[recentBlockhash] requires (length 32) Uint8Array as src
    at el.sendTransaction (665.1ad8f2fdfae3f382.js:1:42460)
    at async 665.1ad8f2fdfae3f382.js:1:48390 el {_events: n, _eventsCount: 4, signTransaction: ƒ, signAllTransactions: ƒ, signMessage: ƒ}
(
```

My code is :

```
    const { connected, publicKey, sendTransaction } = useWallet();

    ....

    const connection = new Connection(clusterApiUrl("devnet"), "confirmed");
    const dmlcoWallet = new PublicKey(<MyWalletPublicKey>); 

      const transaction = new Transaction().add(
        SystemProgram.transfer({
          fromPubkey: publicKey,
          toPubkey: dmlcoWallet,
          lamports: LAMPORTS_PER_SOL * data.pay,
        })
      );
      transaction.feePayer = publicKey ?? profile.value.walletPublicKey;

      let recentHash = await connection.getLatestBlockhash('confirmed');
      transaction.recentBlockhash = recentHash.blockhash;

      const signature = await sendTransaction(transaction, connection,{preflightCommitment: 'confirmed',});


      recentHash = await connection.getLatestBlockhash('confirmed');
      // transaction.recentBlockhash = recentHash.blockhash;

      await connection.confirmTransaction({
        blockhash: recentHash.blockhash,
        lastValidBlockHeight: recentHash.lastValidBlockHeight,
        signature: signature,
      });
```
The code executes to this ponint : `sendTransaction(...)` I run both debug & production on devnet.

**To Reproduce**
Just use the code and build the NextJs app for production and run It.

**Expected behavior**
It should work without bug in production like when I run it on dev mode.

**Comment by jordansexton** [comment]
This is not an error thrown by Wallet Adapter. What wallet are you connected with when calling `sendTransaction`?

**Comment by francestu96** [comment]
Hello, any update on this? I got the same problem...
