### ISSUE TITLE
adapter.on is not a function

### ISSUE THREAD

**Issue by stjkr** [solana-labs/wallet-adapter#795]
Repeatedly getting this error which is breaking the whole script. I guess I am missing one vital thing.

```
import React, { useState, useEffect, useContext, useMemo } from 'react';
import {
    ConnectionProvider,
    WalletProvider,
    WalletContext
} from '@solana/wallet-adapter-react';
import {
    WalletAdapterNetwork
} from '@solana/wallet-adapter-base';
import {
    WalletModalProvider,
    WalletMultiButton
} from '@solana/wallet-adapter-react-ui';

import { PhantomWalletAdapter, PhantomWalletName } from '@solana/wallet-adapter-phantom';
import '@solana/wallet-adapter-react-ui/styles.css';
import { clusterApiUrl } from "@solana/web3.js"

const Start = () => {
const { wallet } = useContext(WalletContext);

    const network = WalletAdapterNetwork.Mainnet;

    const endpoint = useMemo(() => clusterApiUrl(network), [network])

    const wallets = useMemo(
        () => [
            {
                name: PhantomWalletName,
                wallet: PhantomWalletAdapter,
            },
        ],
        [network]
    )
    
useEffect(() => { }, []);

return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletModalProvider>
    <WalletMultiButton />
    </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
};

export default Start;


```

The error more specificially:

```
adapter.on is not a function
TypeError: adapter.on is not a function
    at http://localhost:3000/static/js/bundle.js:84471:41
    at Array.forEach (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:84471:14
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:52703:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:54196:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:54168:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:54158:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:54148:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:56033:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:55985:18)
```

Thanks.

**Comment by nilpferdschaefer** [comment]
You need to remove this line and put it inside a separate component

`const { wallet } = useContext(WalletContext);`

For example:

```
const ComponentThatNeedsWallet = () => {
    const { wallet } = useContext(WalletContext);
    return <>Happy now - i have a wallet</>
};

export default ComponentThatNeedsWallet;
```

And then put that component inside WalletProvider like so

```
<WalletProvider> 
     <ComponentThatNeedsWallet/>
</WalletProvider>
```

This is not strictly Solana-related, it's just how React contexts work - i.e. everything that relies on a context needs to sit inside that context in the hierarchy.

**Comment by jordansexton** [comment]
Thanks @nilpferdschaefer!
