### ISSUE TITLE
WalletConnectionError: Unexpected error at StandardWalletAdapter._StandardWalletAdapter_connect

### ISSUE THREAD

**Issue by DivyanshChaudhary17** [solana-labs/wallet-adapter#833]
**Describe the bug**
**Repo link** - https://github.com/DivyanshChaudhary17/wallet-adapter-issue-repo
// i created this repo only to show error (in console)

// but while hitting connectWallet function i am getting this error -----

WalletConnectionError: Unexpected error
    at StandardWalletAdapter._StandardWalletAdapter_connect (adapter.js:212:1)
    at async Object.connect (WalletProviderBase.js:183:1)
    at async connectWallet (useCustomWallet.tsx:36:1)
    at async connectWalletOrSign (index.tsx:85:1) StandardWalletAdapter {_events: Events, _eventsCount: 4, signIn: ƒ}signIn: async ƒ _StandardWalletAdapter_signIn(input = {})_events: Events {readyStateChange: EE, connect: EE, disconnect: Array(2), error: EE}_eventsCount: 4connected: (...)connecting: (...)icon: (...)name: (...)publicKey: (...)readyState: (...)standard: (...)supportedTransactionVersions: (...)url: (...)wallet: (...)[[Prototype]]: BaseWalletAdapter

**Screenshots**
<img width="1437" alt="image" src="https://github.com/solana-labs/wallet-adapter/assets/104753885/9540f7d3-b28c-41a7-88ac-c59123d3d05a">

**Expected behavior**
The wallet should be connected with phantom wallet extension, it was working fine a few days ago 
suddenly this error appears

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 117.0.5938.132 (Official Build) (arm64)

**Comment by DivyanshChaudhary17** [comment]
@jordansexton Could you please check this is important for a project

**Comment by jordansexton** [comment]
Please use Stack Exchange for questions. Bug reports aren't for support.
